- name: "deploy redis"
  k8s:
    state: present
    definition: "{{lookup('template', 'deployment.yml') }}"
  tags: redis

- name: "deploy redis service"
  k8s:
      state: present
      definition: "{{lookup('template', 'service.yml') }}"
  tags: redis
