---
# Default installation method: "helm" or "k3s_helm"
cert_manager_install_method: "k3s_helm"

cert_manager_chart_version: "v1.19.1"

# Namespace für cert-manager
cert_manager_namespace: "cert-manager"

# Gateway API version for CRDs
gateway_api_version: "v1.0.0"

# Where to store temporary manifest files
cert_manager_tmp_dir: "/tmp"
